blog/urls.py
from django.urls import path, include
from blog import views

urlpatterns = [
    path('', views.ArticleList.as_view()),
    path('drafts/', views.DraftList.as_view(), name='draft_list'),
    path('categories/<slug:title>/', views.CategoryDetails.as_view(), name='category_details'),
    path('<slug:slug>/', views.ArticleDetails.as_view(), name='article_detail'),
]

photoshoppark/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "Photoshop Park"
admin.site.site_title = "Photoshop Park"

urlpatterns = [
    path('', include('home.urls')),
    path('', include('users.urls')), # /profile and login live on the top level
    path('courses/', include('courses.urls')),
    path('blog/', include('blog.urls')),
    path('art/', include('artwork.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')), # tinymce wysiwyg editor
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from users.views import register, profile, signin

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('profile/<slug:username>', profile, name='profile')
]

database/models/course.py
from django.db import models
from django.template.defaultfilters import slugify
from django.views.generic import ListView
from tinymce import models as tinymce_models
from database.models.user import PsUser as User


class Lesson(models.Model):
    title = models.CharField(max_length=120, default="")
    authors = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=240)
    created_on = models.DateField(auto_now_add=True)
    slug = models.CharField(max_length=120, default="")
    image = models.URLField(
        default="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/cute-photos-of-cats-cuddling-1593203046.jpg")
    content = tinymce_models.HTMLField()

    def __str__(self):
        return self.title

    # Automaticly generate slugs on save, admin field also comes prefilled
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Lesson, self).save(*args, **kwargs)


class Course(models.Model):
    lessons = models.ManyToManyField(Lesson, related_name="courses", blank=True)
    title = models.CharField(max_length=120)
    authors = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=240)
    slug = models.CharField(max_length=120, default='')
    image = models.URLField(blank=True,
                            default='https://image-cdn.essentiallysports.com/wp-content/uploads/2022-05'
                                    '-06T155027Z_1312978751_UP1EI561801C4_RTRMADP_3_TENNIS-MADRID.jpg?width=600')

    def __str__(self):
        return self.title

    # autogen slugs again
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Course, self).save(*args, **kwargs)

# Enrollment joining table for the many to many and also progress tracking!
class Enrollment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="courses")
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    progress = models.IntegerField()

database/models/user.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Custom user class because we need enrollments and avatars
class PsUser(AbstractUser):
    username = models.CharField(max_length=64, default='', unique=True)
    avatar = models.URLField(blank=True, default='https://i.scdn.co/image/ab6761610000e5ebfd30ebd7e80dad6b2383aab0')
    email = models.EmailField(max_length=64, unique=True)
    enrollment = models.ManyToManyField('Course', through='Enrollment')

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, UserChangeForm
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox
from database.models.user import PsUser as User


class UserRegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['email'].label = "Email address"
        self.fields['email'].help_text = "Used to recover your account if you lose your password."
        self.fields['password2'].label = "Password Confirmation"

        for field in ['username', 'password1', 'password2']:
            self.fields[field].help_text = None

    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'PhotoshopEnjoyer'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'captcha']


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': '', 'id': 'hello'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': '',
        }
    ))


# class UserAddCourse(UserChangeForm):
#     def __init__(self, *args, **kwargs):
#

users/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect

from django.contrib import messages

from .forms import UserRegistrationForm, UserLoginForm
from database.models.artwork import Artwork
from database.models.course import Course
from database.models.user import PsUser


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)

        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            login(request, user)
            # messages.success(request, f"Welcome to Photoshop Park, {username}!")
            messages.add_message(request, messages.SUCCESS, f"Welcome to Photoshop Park, {username}!")
            return redirect('homepage')
    else:
        form = UserRegistrationForm()

    return render(request, 'users/register.html', {'form': form})


def signin(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, f"Welcome back, {username}!")
            return redirect('homepage')
            # Redirect to a success page.
        else:
            # Return an 'invalid login' error message
            pass

    return


def profile(request, username=None):
    user = PsUser.objects.get(username=username) if username else request.user

    return render(request, 'users/profile.html', {
        'current_user': user,
        'me': user == request.user,
        'art_list': Artwork.objects.filter(authors=user.id).all(),
        'courses': user.enrollment.all()
    })

users/templates/users/login.html
{% extends 'base/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}Log In{% endblock %}

{% block content %}

<div class="stylebg" style="--url: url('https://images.unsplash.com/photo-1584963237956-8059f4b3d0ca?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1900&q=80');"></div>
    <form method="POST">
        {% csrf_token %}
            <div class="container">

                <div class="row justify-content-md-center">
                    <div class="card col-lg-4"
                         style="width: 36rem; border-radius:5px; background-color: rgba(255, 255, 255, 0.6);">
                        <div class="card-body">
                            <h2>Good to see you</h2>
                            <p>Create apps, connect databases and add-on services, and collaborate on your apps, for free.
                               Don't have an account? <a href="{% url 'register' %}">Register</a></p>

                            <div class="row justify-content-center">
                                <div class="col-md-12">
                                    <div class="font-weight-bold">
                                        {{ form.username | as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                            <div class="row justify-content-center">
                                <div class="col-md-12">
                                    <div class="font-weight-bold">
                                        {{ form.password | as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                            <div class="row justify-content-center">
                                <button type="submit" class="btn btn-primary">Log In</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </form>
{% endblock %}

users/templates/users/logout.html
{% extends 'base/base.html' %}
{% block title %} Logged Out {% endblock %}

{% block content %}
    <h1>Goodbye {{ user.name }}!</h1>
    <p><a href="{% url 'login' %}">Log in again</a></p>
{% endblock %}

users/templates/users/profile.html
{% extends 'base/base.html' %}
{% block title %} Profile {% endblock %}

{% block content %}
    <h1 class="display-3 col-12" style="text-align: center">{{ current_user.username }}'s artwork!</h1>

    {% if me %}
        <a href="/logout">Logout</a>
    {% endif %}

    {% with artworks=current_user.artwork.all %}
      <section class="col-10" style="margin: auto">
        {% include 'artwork/art_list.html' %}
      </section>
    {% endwith %}
    <!--
    <h1>Enrolled Courses</h1>
    <section class="flex">
        {% include 'courses/course_list.html' %}
    </section>
    -->
{% endblock %}

users/templates/users/register.html
{% extends 'base/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %} Register {% endblock %}

{% block content %}


<div class="stylebg" style="--url: url('https://mdbootstrap.com/img/Photos/Others/images/76.jpg')"></div>
    <form method="POST">
        {% csrf_token %}
            <div class="container">
                <div class="row justify-content-md-center">
                    <img class="col-sm-1 col-md-1 col-lg-1" src="https://cdn-icons-png.flaticon.com/512/883/883787.png">
                </div>

                <div class="row justify-content-md-center">
                    <div class="card col-lg-4"
                         style="width: 36rem; border-radius:5px; background-color: rgba(255, 255, 255, 0.6);">
                        <div class="card-body">
                            <div class="row justify-content-center">
                                <h2>Join Photoshop Park</h2>
                                <p class="text-center">Self-paced Photoshop learning for everyone, for free.
                                    Already have an account? <a href="{% url 'login' %}">Log in</a></p>
                            </div>
                            <div class="row justify-content-center">
                                <div class="col-md-12">
                                    <div class="font-weight-bold">
                                        {{ form.username | as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                            <div class="row justify-content-center">
                                <div class="col-md-12">
                                    <div class="font-weight-bold">
                                        {{ form.email | as_crispy_field }}
                                    </div>
                                </div>
                            </div>

                            <div class="row justify-content-md-center">
                                <div class="col-md-12">
                                    <div class="font-weight-bold">
                                        {{ form.password1 | as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                            <div class="row justify-content-center">
                                <div class="col-md-12">
                                    <div class="font-weight-bold">
                                        {{ form.password2 | as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                            <div class="row justify-content-center">
                                {{ form.captcha }}

                            </div>
                            <br>
                            <div class="row justify-content-center">
                                <button type="submit" class="btn btn-primary">Register</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </form>
{% endblock %}