blog/urls.py
from django.urls import path, include
from blog import views

urlpatterns = [
    path('', views.ArticleList.as_view()),
    path('drafts/', views.DraftList.as_view(), name='draft_list'),
    path('categories/<slug:title>/', views.CategoryDetails.as_view(), name='category_details'),
    path('<slug:slug>/', views.ArticleDetails.as_view(), name='article_detail'),
]

courses/urls.py
from django.urls import path, include
from courses import views

urlpatterns = [
    path('', views.CourseList.as_view()),
    path('<slug:slug>/', views.CourseDetails.as_view(), name='course-details'),
    path('<slug:course>/<slug:lesson>', views.LessonDetails.as_view(), name='lesson-details')
]

photoshoppark/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "Photoshop Park"
admin.site.site_title = "Photoshop Park"

urlpatterns = [
    path('', include('home.urls')),
    path('', include('users.urls')), # /profile and login live on the top level
    path('courses/', include('courses.urls')),
    path('blog/', include('blog.urls')),
    path('art/', include('artwork.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')), # tinymce wysiwyg editor
]

database/models/course.py
from django.db import models
from django.template.defaultfilters import slugify
from django.views.generic import ListView
from tinymce import models as tinymce_models
from database.models.user import PsUser as User


class Lesson(models.Model):
    title = models.CharField(max_length=120, default="")
    authors = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=240)
    created_on = models.DateField(auto_now_add=True)
    slug = models.CharField(max_length=120, default="")
    image = models.URLField(
        default="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/cute-photos-of-cats-cuddling-1593203046.jpg")
    content = tinymce_models.HTMLField()

    def __str__(self):
        return self.title

    # Automaticly generate slugs on save, admin field also comes prefilled
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Lesson, self).save(*args, **kwargs)


class Course(models.Model):
    lessons = models.ManyToManyField(Lesson, related_name="courses", blank=True)
    title = models.CharField(max_length=120)
    authors = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=240)
    slug = models.CharField(max_length=120, default='')
    image = models.URLField(blank=True,
                            default='https://image-cdn.essentiallysports.com/wp-content/uploads/2022-05'
                                    '-06T155027Z_1312978751_UP1EI561801C4_RTRMADP_3_TENNIS-MADRID.jpg?width=600')

    def __str__(self):
        return self.title

    # autogen slugs again
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Course, self).save(*args, **kwargs)

# Enrollment joining table for the many to many and also progress tracking!
class Enrollment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="courses")
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    progress = models.IntegerField()

courses/views.py
from database.models.course import Course, Lesson
from django.views import generic


class CourseList(generic.ListView):
    model = Course
    queryset = Course.objects.all()
    template_name = 'courses/index.html'
    context_object_name = 'courses'

class CourseDetails(generic.DetailView):
    model = Course
    template_name = 'courses/course_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lessons'] = context['object'].lessons.all()

        return context


class LessonDetails(generic.base.TemplateView):
    template_name = 'courses/lesson_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_course = Course.objects.get(slug=kwargs['course'])

        context['lesson'] = current_course.lessons.get(slug=kwargs['lesson']) # get lesson from course slug
        context['course'] = current_course # for potential lesson lists

        return context

courses/templates/courses/course_details.html
{% extends 'base/base.html' %}

{% block title %} {{course.title}} {% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-12">
            <!-- header-->
            <header class="mb-4">
                <h1 class="h1 mb-1">{{course.title}}</h1>
                <span class="author">By: <a href="/profile/{{course.authors}}">{{course.authors}}</a></span>
                <p class="description">{{course.description}}</p>
                <div class="text-muted fst-italic mb-2"><a href="/">Main page</a> &#9658; <a href="/courses">Courses</a>
                    &#9658; <a href="#">{{course.title}}</a></div>
                <!-- replace src with url -->
                <figure class="mb-4"><img class="img-fluid" width="100%" src="{{ course.image }}"
                        alt="..." />
                </figure>
            </header>

        </div>


    </div>
    {% include 'courses/lesson_list.html' %}
</div>
</article>
{% endblock %}

courses/templates/courses/course_list.html
{% if courses %}
    {% for course in courses %}
      {% include 'partials/course_summary.html' %}
    {% endfor %}
{% else %}
    <article>
        <h1>No courses right now</h1>
        <p>Please come back later!</p>
    </article>
{% endif %}

courses/templates/courses/details.html
{% extends 'base/base.html' %}

{% block title %} {{course.title}} {% endblock %}

{% block content %}
    <article>
        <h1>{{course.title}}</h1>
        <span class="author">By: {{course.authors}}</span>
        <p>{{course.description}}</p>

        <hr>

        {% if lessons %}
            <ul>
                {% for lesson in lessons %}
                    <li>
                        <h2>{{lesson.title}}</h2>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <h2>No lessons available now</h2>
        {% endif %}
    </article>
{% endblock %}

courses/templates/courses/index.html
{% extends 'base/base.html' %}

{% block title %}Courses{% endblock title %}

{% block content %}
        <h1 class=" display-3 col-12" style="text-align: center">Courses</h1>
        <div class="row col-11" style="margin: auto">
            {% include 'courses/course_list.html' %}
        </div>
{% endblock content %}

courses/templates/courses/lesson_details.html
{% extends 'base/base.html' %}

{% block title %} {{ lesson.title }} {% endblock %}

{% block content %}

    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-12">
                <!-- header-->
                <header class="mb-4">
                    <h1 class="h1 mb-1">{{ lesson.title }}</h1>
                    <div class="text-muted fst-italic mb-2">Posted By: {{ lesson.authors }}</div>
                    <div class="text-muted fst-italic mb-2"><a href="/">Main page</a> &#9658; <a href="/courses">Courses</a>
                        &#9658; <a href="/courses/{{ course.slug }}">{{course.title}}</a>  &#9658; <a href="/courses/{{ course.slug }}/{{ lesson.slug }}">{{ lesson.slug }}</a></div>
                    <!-- replace src with url -->
                        <figure class="mb-4"><img class="img-fluid"
                                                  src="{{ lesson.image }}"
                                                  alt="..."/>
                        </figure>
                </header>
                <article class="col-lg-8 mx-auto">
                    <!-- content -->
                    <!-- i simulate longer format with repeated calls, but this should be one thing when launched -->
                    <section class="mb-5">
                        {{ lesson.content | safe }}
                    </section>

                </article>
            </div>


        </div>
    </div>

{% endblock %}

courses/templates/courses/lesson_list.html
{% if lessons %}
      <div class="row">
        {% for lesson in lessons %}
            <div class="item col-sm-6 col-md-4 col-lg-4 mb-4">
                <a href="/courses/{{ course.slug }}/{{ lesson.slug }}" class="item-wrap">
                    <img class="img-fluid" src="{{ lesson.image }}">
                    <div>
                        <h4 class="text-uppercase font-weight-bold text-dark mb-0 mt-1">{{ lesson.title }}</h4>
                        <span class="text-dark">{{ lesson.description }}</span>
                        <br>
                    </div>
                </a>
            </div>
        {% endfor %}
      </div>
{% else %}
    <h2>No lessons available now</h2>
{% endif %}